'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, BookOpen, CalendarDays, CheckCircle2, ClipboardList, GraduationCap, Plus, RefreshCw, ShieldCheck, Users, X } from 'lucide-react'

type User = { id:string; fullName:string; email:string; role:string; studentId?:string; department?:string; course?:string; year?:number; section?:string; semester?:number; phone?:string }

type FormState = { userId:string; code:string; subject:string; present:string; total:string; month:string; fullMonth:string; gpa:string; classAvg:string; credits:string; topSubject:string; topScore:string; title:string; dueDate:string; activity:string; points:string; eventTitle:string; eventDate:string; monthDay:string; time:string; location:string; category:string; badge:string; icon:string }

const blank: FormState = { userId:'', code:'', subject:'', present:'', total:'', month:'', fullMonth:'', gpa:'', classAvg:'', credits:'', topSubject:'', topScore:'', title:'', dueDate:'', activity:'', points:'', eventTitle:'', eventDate:'', monthDay:'', time:'', location:'', category:'', badge:'', icon:'workshop' }

export default function AdminPage() {
  const [users,setUsers]=useState<User[]>([]); const [form,setForm]=useState(blank); const [tab,setTab]=useState('attendance'); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false)
  const students = useMemo(()=>users.filter(u=>u.role==='student'),[users])
  async function load(){ setLoading(true); setError(''); const r=await fetch('/api/admin/users'); const d=await r.json(); if(!r.ok){setError(d.error||'Unable to load users.');setLoading(false);return} setUsers(d.users); setLoading(false) }
  useEffect(()=>{load()},[])
  function set(k:keyof FormState,v:string){setForm(p=>({...p,[k]:v}));setMessage('');setError('')}
  async function submit(path:string, body:Record<string,unknown>){setSaving(true);setMessage('');setError(''); try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed.');setMessage('Saved successfully.');setForm(blank);await load()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setSaving(false)}}
  const studentSelect=<label className="block text-sm font-medium">Student<select value={form.userId} onChange={e=>set('userId',e.target.value)} className="mt-1.5 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.studentId?`${s.studentId} — `:''}{s.fullName}</option>)}</select></label>
  return <main className="min-h-screen bg-background px-4 py-8 text-foreground sm:px-6"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/> Dashboard</Link><h1 className="mt-3 font-display text-3xl font-bold">Faculty & Admin Console</h1><p className="mt-1 text-sm text-muted-foreground">Enter campus records here. Student dashboards read these records automatically.</p></div><button onClick={load} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border px-4 text-sm font-semibold hover:bg-muted"><RefreshCw className="h-4 w-4"/> Refresh</button></div>
    <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={<Users/>} label="Students" value={students.length}/><Stat icon={<GraduationCap/>} label="Faculty" value={users.filter(u=>u.role==='faculty').length}/><Stat icon={<ShieldCheck/>} label="Admins" value={users.filter(u=>u.role==='admin').length}/><Stat icon={<CheckCircle2/>} label="Data source" value="Database"/></div>
    <div className="grid gap-6 lg:grid-cols-[220px_1fr]">
      <nav className="rounded-2xl border border-border bg-card p-2 h-fit">{[['attendance','Attendance',ClipboardList],['performance','Performance',GraduationCap],['assignments','Assignments',BookOpen],['participation','Participation',CheckCircle2],['events','Events',CalendarDays]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold ${tab===id?'bg-primary text-primary-foreground':'hover:bg-muted'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>
      <section className="rounded-2xl border border-border bg-card p-5 sm:p-7">
        {tab==='attendance'&&<><Title icon={<ClipboardList/>} title="Record attendance"/><div className="grid gap-4 sm:grid-cols-2">{studentSelect}<Field label="Subject" value={form.subject} onChange={v=>set('subject',v)} placeholder="DBMS"/><Field label="Subject code" value={form.code} onChange={v=>set('code',v)} placeholder="CS301"/><Field label="Present classes" type="number" value={form.present} onChange={v=>set('present',v)} placeholder="38"/><Field label="Total classes" type="number" value={form.total} onChange={v=>set('total',v)} placeholder="42"/></div><Action onClick={()=>submit('/api/attendance',{userId:form.userId,subject:form.subject,code:form.code,present:Number(form.present),total:Number(form.total)})} saving={saving}/></>}
        {tab==='performance'&&<><Title icon={<GraduationCap/>} title="Record academic performance"/><div className="grid gap-4 sm:grid-cols-2">{studentSelect}<Field label="Month code" value={form.month} onChange={v=>set('month',v)} placeholder="S1"/><Field label="Result / semester" value={form.fullMonth} onChange={v=>set('fullMonth',v)} placeholder="Semester 1"/><Field label="GPA / SGPA" type="number" value={form.gpa} onChange={v=>set('gpa',v)} placeholder="8.75"/><Field label="Class average" type="number" value={form.classAvg} onChange={v=>set('classAvg',v)} placeholder="7.80"/><Field label="Credits" type="number" value={form.credits} onChange={v=>set('credits',v)} placeholder="24"/><Field label="Top subject" value={form.topSubject} onChange={v=>set('topSubject',v)} placeholder="DBMS"/><Field label="Top score" value={form.topScore} onChange={v=>set('topScore',v)} placeholder="92"/></div><Action onClick={()=>submit('/api/performance',{userId:form.userId,month:form.month,fullMonth:form.fullMonth,gpa:Number(form.gpa),classAvg:Number(form.classAvg),credits:Number(form.credits),topSubject:form.topSubject,topScore:form.topScore})} saving={saving}/></>}
        {tab==='assignments'&&<><Title icon={<BookOpen/>} title="Create assignment"/><div className="grid gap-4 sm:grid-cols-2">{studentSelect}<Field label="Assignment title" value={form.title} onChange={v=>set('title',v)} placeholder="DBMS Normalization Worksheet"/><Field label="Due date" type="date" value={form.dueDate} onChange={v=>set('dueDate',v)}/></div><Action onClick={()=>submit('/api/assignments',{userId:form.userId,title:form.title,dueDate:form.dueDate})} saving={saving}/></>}
        {tab==='participation'&&<><Title icon={<CheckCircle2/>} title="Record campus participation"/><div className="grid gap-4 sm:grid-cols-2">{studentSelect}<Field label="Activity" value={form.activity} onChange={v=>set('activity',v)} placeholder="Hackathon participation"/><Field label="Points" type="number" value={form.points} onChange={v=>set('points',v)} placeholder="10"/></div><Action onClick={()=>submit('/api/participation',{userId:form.userId,activity:form.activity,points:Number(form.points)})} saving={saving}/></>}
        {tab==='events'&&<><Title icon={<CalendarDays/>} title="Create campus event"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Event title" value={form.eventTitle} onChange={v=>set('eventTitle',v)} placeholder="Google Developer Workshop"/><Field label="Date" type="date" value={form.eventDate} onChange={v=>set('eventDate',v)}/><Field label="Month / day label" value={form.monthDay} onChange={v=>set('monthDay',v)} placeholder="OCT 09"/><Field label="Time" value={form.time} onChange={v=>set('time',v)} placeholder="10:00 AM"/><Field label="Location" value={form.location} onChange={v=>set('location',v)} placeholder="Seminar Hall"/><Field label="Category" value={form.category} onChange={v=>set('category',v)} placeholder="Workshop"/><Field label="Badge" value={form.badge} onChange={v=>set('badge',v)} placeholder="Technical"/><label className="block text-sm font-medium">Icon<select value={form.icon} onChange={e=>set('icon',e.target.value)} className="mt-1.5 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="workshop">Workshop</option><option value="hackathon">Hackathon</option><option value="meetup">Meetup</option></select></label></div><Action onClick={()=>submit('/api/events',{title:form.eventTitle,date:form.eventDate,monthDay:form.monthDay,time:form.time,location:form.location,category:form.category,badge:form.badge,icon:form.icon})} saving={saving}/></>}
        {message&&<p className="mt-5 rounded-lg bg-success/10 px-3 py-2 text-sm text-success">{message}</p>}{error&&<p className="mt-5 rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}
      </section>
    </div>
    <section className="mt-6 rounded-2xl border border-border bg-card p-5"><h2 className="font-display text-lg font-semibold">Registered students</h2>{loading?<p className="mt-3 text-sm text-muted-foreground">Loading…</p>:students.length===0?<p className="mt-3 text-sm text-muted-foreground">No students yet. Students can register from the signup page.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted-foreground"><th className="p-2">Student</th><th className="p-2">Roll No.</th><th className="p-2">Department</th><th className="p-2">Course</th><th className="p-2">Year / Sem</th><th className="p-2">Section</th></tr></thead><tbody>{students.map(s=><tr key={s.id} className="border-b border-border/60"><td className="p-2 font-medium">{s.fullName}<div className="text-xs text-muted-foreground">{s.email}</div></td><td className="p-2">{s.studentId||'—'}</td><td className="p-2">{s.department||'—'}</td><td className="p-2">{s.course||'—'}</td><td className="p-2">{s.year?`${s.year} / ${s.semester||'—'}`:'—'}</td><td className="p-2">{s.section||'—'}</td></tr>)}</tbody></table></div>}</section>
  </div></main>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:React.ReactNode}){return <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2 text-primary">{icon}<span className="text-xs font-semibold text-muted-foreground">{label}</span></div><div className="mt-2 font-display text-2xl font-bold">{value}</div></div>}
function Title({icon,title}:{icon:React.ReactNode;title:string}){return <div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</span><h2 className="font-display text-xl font-semibold">{title}</h2></div>}
function Field({label,value,onChange,placeholder,type='text'}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="block text-sm font-medium">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-1.5 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm focus:border-primary focus:outline-none focus:ring-4 focus:ring-primary/15"/></label>}
function Action({onClick,saving}:{onClick:()=>void;saving:boolean}){return <button onClick={onClick} disabled={saving} className="mt-6 inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:opacity-60"><Plus className="h-4 w-4"/>{saving?'Saving…':'Save record'}</button>}
